# Generated by Django 4.0.6 on 2022-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_profile_picure'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
