# Generated by Django 4.0.6 on 2022-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default='5', max_length=10000),
        ),
    ]
