# Generated by Django 4.0.6 on 2022-10-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orders_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
