# Generated by Django 4.0.6 on 2022-10-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picure',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Image files only'}, null=True, upload_to=''),
        ),
    ]
