# Generated by Django 4.0.6 on 2022-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
