# Generated by Django 4.0.6 on 2022-11-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coupon'),
        ),
    ]
