# Generated by Django 4.0.6 on 2022-11-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_orderitems_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='seller',
            new_name='user',
        ),
    ]
