# Generated by Django 4.0.6 on 2022-11-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_seller_orderitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='main.address'),
        ),
    ]
