# Generated by Django 4.0.6 on 2022-12-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_orderitems_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='coupon',
        ),
        migrations.AddField(
            model_name='orders',
            name='Buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
