# Generated by Django 4.0.6 on 2022-12-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_orderitems_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Buyer',
            new_name='buyer',
        ),
    ]
